

spring:
    profiles:
      active: local


    datasource:
        url: jdbc:mysql://swiftsjh.tplinkdns.com:3306/test
        username: dmz
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show_sql: true

logging:
    level:
        com.tutorial: debug
server:
    ssl:
        enabled: true
        key-store: src/main/resources/kanu-keystore.p12
        key-store-password: 123456
        key-store-type: PKCS12
        key-alias: kanu-keystore
    port: 8080
    http2:
        enabled: true

jwt:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK